package com.kaiharimoto.mastertool.core.port

import com.kaiharimoto.mastertool.core.board.DropIntent
import com.kaiharimoto.mastertool.core.board.FieldZone
import com.kaiharimoto.mastertool.core.board.CardPosition
import com.kaiharimoto.mastertool.core.board.MatPoint
import com.kaiharimoto.mastertool.core.board.BoardCard
import com.kaiharimoto.mastertool.core.board.DragOrigin
import com.kaiharimoto.mastertool.core.board.DropCommit
import com.kaiharimoto.mastertool.core.board.DropTargets
import com.kaiharimoto.mastertool.core.board.FanHome
import com.kaiharimoto.mastertool.core.board.PlacedCard
import com.kaiharimoto.mastertool.core.board.PlayField
import com.kaiharimoto.mastertool.core.board.toMat
import com.kaiharimoto.mastertool.core.board.SetPosition
import com.kaiharimoto.mastertool.core.layout.BoardLayouter
import com.kaiharimoto.mastertool.core.model.CardId
import com.kaiharimoto.mastertool.core.layout.BoardSlot
import com.kaiharimoto.mastertool.core.input.MatGuide
import com.kaiharimoto.mastertool.core.layout.HandFan
import com.kaiharimoto.mastertool.core.layout.HandRow
import com.kaiharimoto.mastertool.core.motion.SpringSpec
import com.kaiharimoto.mastertool.core.motion.SpringValue
import com.kaiharimoto.mastertool.core.motion.Springs
import com.kaiharimoto.mastertool.core.ydk.YdkCodec
import kotlin.random.Random
import java.io.File
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * Writes the golden vectors the 3DS port is held to.
 *
 * ## Why this is a test and not a tool
 *
 * `3ds/src/core/` is a hand-written C translation of the arithmetic in this
 * module. A translation nobody checks is a fork, and it drifts silently: the
 * tablet and the console would each be internally consistent and disagree about
 * where a card lands, which is the class of bug that takes a week to see.
 *
 * So the C is held to *this* module's output rather than to a second reading of
 * the same intent. This test sweeps each ported function over a fixed grid of
 * inputs and writes the answers to `3ds/test/vectors/`; `3ds/test/mt_test.c`
 * compiles the C on the host and asserts against the same file.
 *
 * ## The vectors are committed on purpose
 *
 * They are checked in, and CI runs `git diff --exit-code` over them after this
 * test. That makes the consequence visible in the only place it can be argued
 * about: a change to `BoardLayouter` that moves a zone shows up in review as a
 * diff in a vector file, next to the change that caused it. A regenerated
 * vector file is not a failure — it is the author being asked to notice that
 * the console's table just moved too, and to say so in the message.
 *
 * Nothing here asserts behaviour. `BoardLayoutTest` and the rest of commonTest
 * are where the rules are argued; this only records what they currently answer.
 */
class GoldenVectorExportTest {

    /**
     * Nine significant digits, because that is what round-trips an IEEE 754
     * single exactly. Fewer and the C would be asserted against a number the
     * Kotlin never produced, and the tolerance would have to absorb the
     * difference — which is the tolerance absorbing a bug.
     */
    private fun f(value: Float): String = String.format("%.9g", value)

    private fun b(value: Boolean): String = if (value) "1" else "0"

    /**
     * Walks up from the module directory to the repository root.
     *
     * The Gradle test working directory is the project dir (`app/core`), but
     * that is a default rather than a promise, and a hard `../../` would break
     * silently the day it changed — writing the vectors somewhere nobody looks
     * while still passing.
     */
    private fun vectorDir(): File {
        var dir: File? = File(".").absoluteFile
        while (dir != null) {
            val candidate = File(dir, "3ds/test/vectors")
            if (File(dir, "3ds").isDirectory) {
                candidate.mkdirs()
                return candidate
            }
            dir = dir.parentFile
        }
        error("no 3ds/ directory above ${File(".").absolutePath}")
    }

    private fun write(name: String, header: String, lines: List<String>) {
        val file = File(vectorDir(), name)
        file.writeText(
            buildString {
                appendLine("# generated by GoldenVectorExportTest - do not edit by hand")
                appendLine("# $header")
                lines.forEach { appendLine(it) }
            }
        )
        assertTrue(lines.isNotEmpty(), "$name would be empty, which asserts nothing")
    }

    @Test
    fun `mat guide console idioms`() {
        // The one vector that carries no arithmetic, and it is here rather than
        // in a Kotlin test because the thing it has to agree with is in C.
        //
        // `MatGuide` is the tablet's guide and `3ds/src/core/mt_input.h` is the
        // console's, and they are two lists because the console has controls a
        // table does not - undo, phases, life points, quit. What may not differ
        // is the *overlap*: a gesture the tablet's guide says is on L must be on
        // L in the list the console renders. Exported one way on purpose - every
        // button named here must exist there; a console-only row is not a drift.
        //
        // Pipe-separated because a button is "ZL / ZR" and a gesture is a
        // sentence, and the suite's whitespace splitter would make eleven fields
        // of either.
        val lines = MatGuide.all.mapNotNull { gesture ->
            gesture.button?.let { "$it|${gesture.what}" }
        }
        write("matguide.txt", "<button>|<gesture> - every console idiom the tablet names", lines)
    }

    @Test
    fun `board layout solve`() {
        // Both 3DS screens, both tablet ends of docs/classic/DEVICES.md's matrix, and
        // the degenerate inputs the solver is documented to survive: a zero
        // width, an aspect ratio of zero, a growth below one and a roomAbove
        // past its own clamp.
        val widths = listOf(320f, 400f, 640f, 1480f, 0f)
        val heights = listOf(240f, 360f, 924f)
        val ratios = listOf(0.686f, 1f, 0f)
        val growths = listOf(1f, 1.35f, 0.5f)
        val rooms = listOf(0f, 0.2f, 0.9f)

        val lines = buildList {
            for (w in widths) for (h in heights) for (r in ratios)
                for (g in growths) for (room in rooms) {
                    val l = BoardLayouter.solve(w, h, r, g, room)
                    add(
                        listOf(
                            f(w), f(h), f(r), f(g), f(room), "=",
                            f(l.cardWidth), f(l.cardHeight), f(l.gap), b(l.fits),
                            f(l.field.left), f(l.field.top), f(l.field.width), f(l.field.height),
                            f(l.hand.left), f(l.hand.top), f(l.hand.width), f(l.hand.height),
                            f(l.readout.left), f(l.readout.top),
                            f(l.readout.width), f(l.readout.height),
                            f(l.bounds.left), f(l.bounds.top),
                            f(l.bounds.width), f(l.bounds.height),
                        ).joinToString(" ")
                    )
                }
        }
        write(
            "board_solve.txt",
            "w h ratio growth room = cardW cardH gap fits " +
                "fieldLTWH handLTWH readoutLTWH boundsLTWH",
            lines,
        )
    }

    /** The seventeen slots, in the insertion order `slotAt` resolves ties by. */
    @Test
    fun `board layout slots`() {
        val layout = BoardLayouter.solve(400f, 240f, 0.686f, 1f, 0f)
        val lines = layout.slots.entries.map { (slot, rect) ->
            "${slotName(slot)} = ${f(rect.left)} ${f(rect.top)} ${f(rect.width)} ${f(rect.height)}"
        }
        write("board_slots.txt", "slot = left top width height (INSERTION ORDER)", lines)
    }

    /**
     * `slotAt` over a grid finer than the gap between zones.
     *
     * The point is the midlines. Each slot claims half the gap around it, so
     * neighbours meet exactly on the boundary and the first in insertion order
     * takes it — which is a fact about a LinkedHashMap in Kotlin and about an
     * array index in C, and the only way to know those still agree is to ask
     * them both about a point that lands on one.
     */
    @Test
    fun `board layout slot at`() {
        val layout = BoardLayouter.solve(400f, 240f, 0.686f, 1f, 0f)
        val lines = buildList {
            var iy = 0
            while (iy <= 48) {
                var ix = 0
                while (ix <= 80) {
                    val x = ix * 5f
                    val y = iy * 5f
                    val hit = layout.slotAt(x, y)
                    add("${f(x)} ${f(y)} = ${hit?.let(::slotName) ?: "-"}")
                    ix++
                }
                iy++
            }
        }
        write("board_slot_at.txt", "x y = slot-or-dash (layout 400x240 r0.686 g1 room0)", lines)
    }

    @Test
    fun `set position`() {
        val zones: List<Pair<String, DropIntent?>> = listOf(
            "none" to null,
            "free" to DropIntent.Free(MatPoint(0.5f, 0.5f)),
            "monster" to DropIntent.Zone(BoardSlot.Zone(FieldZone.Monster(2)), MatPoint(0.5f, 0.5f)),
            "extra" to DropIntent.Zone(BoardSlot.Zone(FieldZone.ExtraMonster(0)), MatPoint(0.5f, 0.5f)),
            "spell" to DropIntent.Zone(BoardSlot.Zone(FieldZone.SpellTrap(1)), MatPoint(0.5f, 0.5f)),
            "field" to DropIntent.Zone(BoardSlot.Zone(FieldZone.FieldSpell), MatPoint(0.5f, 0.5f)),
            "deckslot" to DropIntent.Zone(BoardSlot.Deck, MatPoint(0.5f, 0.5f)),
            "stack" to DropIntent.Stack(7),
            "hand" to DropIntent.Hand(2),
            "graveyard" to DropIntent.Graveyard,
            "cancel" to DropIntent.Cancel,
        )
        val monsters: List<Pair<String, Boolean?>> =
            listOf("no" to false, "yes" to true, "unknown" to null)

        val lines = buildList {
            for (faceDown in listOf(false, true))
                for (turned in listOf(false, true))
                    for ((zoneName, intent) in zones)
                        for ((monsterName, monster) in monsters) {
                            val position = SetPosition.of(faceDown, turned, intent, monster)
                            add(
                                "${b(faceDown)} ${b(turned)} $zoneName $monsterName = ${position.name}"
                            )
                        }
        }
        write("set_position.txt", "faceDown turned intent monster = position", lines)
    }

    /**
     * Spring trajectories, stepped rather than sampled.
     *
     * A spring is not a function of its inputs, it is a function of its own
     * previous state, so a vector that checked one step would pass on an
     * integrator that had the order wrong. Semi-implicit Euler advances the
     * velocity first and the position with the *new* velocity; explicit Euler
     * uses the old one, injects energy, and diverges on a stiff spring. Those
     * two agree closely for one step and visibly disagree after forty, which is
     * why every step of every trajectory is written down.
     *
     * The dt list is deliberately awkward: a 60Hz frame, a 30Hz frame, one past
     * MAX_STEP so the clamp is exercised, and a zero.
     */
    @Test
    fun `spring trajectories`() {
        val specs = listOf(
            "snappy" to SpringSpec.Snappy,
            "bouncy" to SpringSpec.Bouncy,
            "calm" to SpringSpec.Calm,
        )
        val starts = listOf(0f to 0f, 120f to 0f, 40f to -900f)
        val targets = listOf(0f, 100f)
        val dts = listOf(1f / 60f, 1f / 30f, 0.25f, 0f)

        val lines = buildList {
            for ((specName, spec) in specs)
                for ((v0, vel0) in starts)
                    for (target in targets)
                        for (dt in dts) {
                            var state = SpringValue(v0, vel0)
                            for (i in 0 until 40) {
                                state = Springs.step(state, target, spec, dt)
                                add(
                                    "$specName ${f(v0)} ${f(vel0)} ${f(target)} ${f(dt)} $i " +
                                        "= ${f(state.value)} ${f(state.velocity)} " +
                                        b(Springs.settled(state, target))
                                )
                            }
                        }
        }
        write(
            "spring.txt",
            "spec v0 vel0 target dt step = value velocity settled",
            lines,
        )
    }

    /**
     * Deck files, parsed by both sides from byte-identical inputs.
     *
     * The synthetic cases are *written out as real files* rather than described,
     * so that the C reads exactly what the Kotlin read. A vector that quoted an
     * input inside itself would need two escapings to agree, and the first
     * disagreement between them would look like a parser bug.
     *
     * They are the awkward ones on purpose: a CRLF file, a UTF-8 BOM, a file
     * with no section marker at all, `!side` before `#extra`, junk lines, a
     * `#Created By` in the wrong case (which the Kotlin matches
     * case-insensitively and then strips case-*sensitively*, keeping the whole
     * string - a quirk the port reproduces rather than corrects), and a
     * `#ydkx-extended` block that is not readable and must be dropped.
     */
    @Test
    fun `ydk documents`() {
        val dir = File(vectorDir(), "case")
        dir.mkdirs()

        val cases = linkedMapOf(
            "plain.ydk" to "#main\n46986414\n46986414\n#extra\n#side\n",
            "crlf.ydk" to "#main\r\n46986414\r\n89631139\r\n!side\r\n38033121\r\n",
            "bom.ydk" to "\uFEFF#main\n46986414\n",
            "no-marker.ydk" to "46986414\n89631139\n",
            "side-first.ydk" to "#main\n46986414\n!side\n38033121\n#extra\n1861629\n",
            "junk.ydk" to "#main\n46986414\nnot-a-card\n  \n12x34\n89631139\n",
            "created-wrong-case.ydk" to "#Created By kai\n#main\n46986414\n",
            "created-lower.ydk" to "#created by kai\n#main\n46986414\n",
            "comment.ydk" to "#this is a comment\n#main\n46986414\n",
            "negative.ydk" to "#main\n-46986414\n46986414\n",
            "huge-id.ydk" to "#main\n999999999999\n46986414\n",
            "ydkx-good.ydkx" to
                "#main\n46986414\n#ydkx-extended\n{\"groups\":[{\"name\":\"Starters\"}],\"notes\":{}}\n",
            "ydkx-broken.ydkx" to "#main\n46986414\n#ydkx-extended\n{\"groups\": [\n",
            "ydkx-empty.ydkx" to "#main\n46986414\n#ydkx-extended\n",
        )
        cases.forEach { (name, body) -> File(dir, name).writeText(body) }

        // The real ones too. A synthetic suite proves the edge cases; a deck
        // somebody actually built proves the ordinary case, which is the one
        // that has to work on the console.
        // Labelled by where they came from, not by their file name. The
        // repository holds *two different decks* both called lab.ydkx - one at
        // the root and one in ydk/ - so a label of `it.name` silently gave two
        // inputs the same key, and the conformance suite read the first file
        // twice while comparing it against the second file's answers.
        val repo = vectorDir().parentFile.parentFile.parentFile
        val real = buildList {
            add(File(repo, "lab.ydkx"))
            File(repo, "ydk").listFiles()?.sortedBy { it.name }?.let(::addAll)
        }

        val entries = cases.keys.map { "case/$it" to File(dir, it) } +
            real.filter { it.isFile }.map { "repo/${it.relativeTo(repo).invariantSeparatorsPath}" to it }

        val lines = buildList {
            for ((label, file) in entries) {
                val result = YdkCodec.parse(file.readText())
                val doc = result.document
                add("$label ydkx ${b(doc.isYdkx)}")
                add("$label warnings ${result.warnings.size}")
                add("$label main ${doc.deck.main.size} ${doc.deck.main.joinToString(" ") { it.value.toString() }}".trim())
                add("$label extra ${doc.deck.extra.size} ${doc.deck.extra.joinToString(" ") { it.value.toString() }}".trim())
                add("$label side ${doc.deck.side.size} ${doc.deck.side.joinToString(" ") { it.value.toString() }}".trim())
                // Last, and taking the rest of the line, because a name may
                // contain spaces and this format splits on them.
                add("$label created ${doc.createdBy ?: "-"}")
            }
        }
        write("ydk.txt", "<file> <key> <values...>  (case/* live in vectors/case/, repo/* at the repo root)", lines)
    }

    /**
     * The generator itself, before anything that uses it.
     *
     * `PlayField.riffled` writes Fisher-Yates out by hand instead of calling
     * `shuffled(Random(seed))`, and its comment says why: the standard library
     * may change its algorithm between versions and platforms, and a seed that
     * dealt one hand on a tablet and another on a desktop would make every bug
     * report about an opening hand unreproducible.
     *
     * That reasoning does not survive a port unless the *generator* crosses over
     * with it. An identical Fisher-Yates fed by a different PRNG is a shuffle
     * that is correct, deterministic and a different deal — the very failure the
     * hand-written loop exists to prevent, walking in through the one door it
     * left open. So `kotlin.random.Random` — XorWow, not `java.util.Random` — is
     * reproduced in C, and this is what holds it there.
     *
     * The bounds are chosen to hit both branches of `nextInt(until)`: powers of
     * two take the upper bits directly, everything else goes through a modulo
     * with a rejection loop for the short tail.
     */
    @Test
    fun `kotlin random`() {
        val seeds = listOf(0L, 1L, 7L, 42L, -1L, 1234567890123L, Long.MIN_VALUE, Long.MAX_VALUE)
        val bounds = listOf(2, 3, 5, 8, 16, 17, 40, 60, 1000, 65536)

        val lines = buildList {
            for (seed in seeds) {
                // The raw stream first, which pins seeding and the 64 discarded
                // outputs independently of any bound arithmetic.
                val raw = Random(seed)
                for (i in 0 until 24) add("raw $seed $i = ${raw.nextInt()}")

                for (bound in bounds) {
                    val random = Random(seed)
                    for (i in 0 until 16) {
                        add("bound $seed $bound $i = ${random.nextInt(bound)}")
                    }
                }
            }
        }
        write("random.txt", "raw <seed> <i> = <int>  |  bound <seed> <bound> <i> = <int>", lines)
    }

    /**
     * The table itself, driven by a script that lives in the vector file.
     *
     * `PlayField` is the one ported thing that is *stateful*, and that changes
     * what a vector has to be. A function can be swept over a grid of inputs; a
     * table has to be walked, because each operation's correctness depends on
     * every operation before it.
     *
     * So the script is written **into the file** rather than duplicated in both
     * languages, and it is built **as it runs**, against the live field. The
     * first version of this test hardcoded instance ids, and after a shuffle
     * those ids are somewhere else — so `stack`, `attach`, `counter` and
     * `takeFromUnder` were all quietly *refused*, the suite recorded the
     * refusals faithfully on both sides, and 25,945 checks passed without ever
     * executing the code they were written for. Two deliberate mutations went
     * undetected before that was noticed.
     *
     * Refusals still matter and are still recorded — `ok 0` is a real answer,
     * and the state after one is compared too, because the Kotlin gets "the
     * field is unchanged" free from immutability and the C has to earn it. But
     * a refusal has to be *chosen*, not stumbled into.
     */
    @Test
    fun `play field script`() {
        // Distinct passcodes, so a card in the wrong pile is visible rather
        // than plausible.
        val main = (1..24).map { CardId(1000 + it) }
        val extra = (1..6).map { CardId(9000 + it) }

        var field = PlayField.setUp(main, extra)
        val lines = mutableListOf<String>()
        var step = 0

        fun position(raw: Int): CardPosition? =
            if (raw >= CardPosition.entries.size) null else CardPosition.entries[raw]

        fun record(ok: Boolean) {
            lines += "$step ok ${b(ok)}"
            lines += "$step lp ${field.lifePoints} phase ${field.phase.ordinal} turn ${field.turn}"
            lines += "$step mat ${field.mat.size}"
            field.mat.forEachIndexed { i, placed ->
                val sb = StringBuilder("$step mat$i ${placed.id} ${placed.card.cardId.value} ")
                sb.append("${f(placed.at.x)} ${f(placed.at.y)} ")
                sb.append("${placed.card.position.ordinal} ${placed.card.counters} ")
                sb.append("${placed.beneath.size}")
                placed.beneath.forEach { sb.append(" ${it.instanceId}") }
                sb.append(" ${placed.card.materials.size}")
                placed.card.materials.forEach { sb.append(" ${it.instanceId}") }
                lines += sb.toString()
            }
            // Position and counters travel with a card into a pile, and used to
            // be dropped here — which made `lift` clearing counters and
            // `toBanish` setting face-down both invisible. A mutation that left
            // counters on a card sent to the graveyard passed cleanly.
            fun pile(name: String, cards: List<com.kaiharimoto.mastertool.core.board.BoardCard>) {
                lines += "$step $name ${cards.size}" + cards.joinToString("") {
                    " ${it.instanceId} ${it.position.ordinal} ${it.counters}"
                }
            }
            pile("hand", field.hand)
            pile("deck", field.deck)
            pile("extra", field.extraDeck)
            pile("gy", field.graveyard)
            pile("ban", field.banished)
        }

        fun run(raw: String) {
            step += 1
            val parts = raw.trim().split(" ")
            val op = parts[0]
            fun i(n: Int) = parts[n].toInt()
            fun p(n: Int) = parts[n].toFloat()
            fun at(n: Int) = MatPoint(p(n), p(n + 1))

            val next: PlayField? = when (op) {
                "shuffle" -> field.shuffleDeck(parts[1].toLong())
                "draw" -> field.draw()
                "playhand" -> field.playFromHand(i(1), at(2), CardPosition.entries[i(4)])
                "playdeck" -> field.playFromDeck(i(1), at(2), CardPosition.entries[i(4)])
                "playextra" -> field.playFromExtra(i(1), at(2), CardPosition.entries[i(4)])
                "playgy" -> field.playFromGraveyard(i(1), at(2), CardPosition.entries[i(4)])
                "playban" -> field.playFromBanished(i(1), at(2), CardPosition.entries[i(4)])
                "move" -> field.moveOnMat(i(1), at(2), position(i(4)))
                "stack" -> field.stackOnto(i(1), i(2), position(i(3)))
                "unstack" -> field.unstack(i(1), at(2))
                "front" -> field.bringToFront(i(1))
                "flip" -> field.flip(i(1))
                "rotate" -> field.rotate(i(1))
                "setpos" -> field.setPosition(i(1), CardPosition.entries[i(2)])
                "gy" -> field.toGraveyard(i(1))
                "banish" -> field.toBanish(i(1), i(2) != 0)
                "tohand" -> field.toHand(i(1), i(2).takeIf { it >= 0 })
                "decktop" -> field.toDeckTop(i(1))
                "deckbottom" -> field.toDeckBottom(i(1))
                "toextra" -> field.toExtraDeck(i(1))
                "handgy" -> field.handToGraveyard(i(1))
                "handbanish" -> field.handToBanish(i(1))
                "handdecktop" -> field.handToDeckTop(i(1))
                "handdeckbottom" -> field.handToDeckBottom(i(1))
                "reorder" -> field.reorderHand(i(1), i(2))
                "counter" -> field.addCounter(i(1), i(2))
                "attach" -> field.attachAsMaterial(i(1), i(2))
                "detach" -> field.detachMaterial(i(1))
                // The position is ignored when the index is 0 — that path is a
                // plain slide of the top card — which is exactly the asymmetry
                // the C has to reproduce rather than tidy away.
                "takefromunder" -> field.takeFromUnder(i(1), i(2), at(3), CardPosition.entries[i(5)])
                "life" -> field.adjustLifePoints(i(1))
                "phase" -> field.nextPhase()
                "endturn" -> field.endTurn()
                else -> error("unknown op '$op'")
            }

            lines += "$step op $raw"
            if (next != null) field = next
            record(next != null)
        }

        /** The instance on the mat at [index] from the back, so ops name real cards. */
        fun onMat(index: Int) = field.mat[index].id
        fun top() = field.mat.last().id

        record(true)   // step 0

        run("shuffle 20260820")
        repeat(6) { run("draw") }

        // Four cards down, so there is something to build piles out of.
        run("playhand 0 0.30 0.40 0")
        run("playhand 0 0.50 0.40 2")
        run("playhand 0 0.70 0.40 1")
        run("playhand 0 0.20 0.60 0")

        val a = onMat(0); val bCard = onMat(1); val c = onMat(2); val d = onMat(3)

        run("move $a 0.32 0.45 4")          // 4 == keep
        run("move $bCard 0.50 0.42 0")
        run("front $a")
        run("front ${top()}")               // already there: refused
        run("flip $bCard")
        run("rotate $a")
        run("setpos $c 3")

        // Two piles of two, then one pile onto the other — the only shape that
        // exercises the order `beneath` is concatenated in.
        run("stack $a $bCard 4")
        run("stack $c $d 4")
        run("stack $a $c 4")
        run("stack $a $a 4")                // onto itself: refused

        run("counter $a 3")
        run("takefromunder $a 2 0.15 0.55 0")
        run("takefromunder $a 0 0.16 0.56 2")   // index 0 ignores the position
        run("unstack $a 0.20 0.20")

        run("playdeck 0 0.10 0.10 0")
        run("playdeck 99 0.10 0.10 0")      // out of range: refused
        run("playextra 0 0.90 0.10 1")

        val host = top()
        val guest = onMat(0)
        run("attach $guest $host")
        run("attach $host $host")           // onto itself: refused
        run("detach $host")
        run("detach $host")                 // nothing attached now: refused

        // A card with counters leaving the mat, so `lift` clearing them is seen.
        run("counter $host 4")
        run("gy $host")

        run("banish ${top()} 1")            // face-down, which the pile must show
        run("tohand ${top()} 0")
        run("decktop ${top()}")
        if (field.mat.isNotEmpty()) run("deckbottom ${top()}")
        if (field.mat.isNotEmpty()) run("toextra ${top()}")

        // Enough cards in hand that reordering has somewhere to go. Without
        // this the hand held one card by now, `ints_insert_at` clamped both
        // branches of reorderHand's `to > from` adjustment to the same place,
        // and a mutation deleting that adjustment passed cleanly.
        repeat(5) { run("draw") }
        run("reorder 0 3")
        run("reorder 3 0")
        run("reorder 1 4")
        run("reorder 4 2")

        run("handgy 0")
        run("handbanish 0")
        run("handdecktop 0")
        run("handdeckbottom 0")
        run("reorder 0 2")
        run("reorder 1 1")                  // its own place: refused
        run("reorder 1 2")                  // the gap after itself: refused

        run("playgy 0 0.40 0.80 0")
        run("playban 0 0.60 0.80 0")
        run("counter ${top()} -99")         // clamps to zero
        run("counter ${top()} 0")           // no change: refused

        run("life -1200")
        run("life -99999")                  // clamps to zero
        run("phase"); run("phase"); run("endturn")
        run("shuffle -7")

        write("playfield.txt", "<step> op <script line> then the whole field, keyed by step", lines)
    }

    /**
     * The hand's row, and the inverse that has to land back on it.
     *
     * `insertAt` is the true inverse of `centreOf` only because it *counts*
     * drawn cards rather than dividing by the step — a row with a place held
     * open in it is not evenly spaced, and dividing describes a row that is.
     * The property worth pinning is the fixed point: the gap `insertAt` names
     * for a point is the gap the row is already holding open there. A row that
     * re-asked and got a different answer would flicker every frame.
     *
     * The 3DS draws this as a strip rather than a fan, but a strip with a gap
     * open in it is the same question, so the same arithmetic answers it.
     */
    @Test
    fun `hand fan`() {
        val layout = BoardLayouter.solve(320f, 226f, 0.686f, 1f, 0f)
        val band = layout.hand
        val stepFraction = 0.74f

        val lines = buildList {
            for (count in listOf(0, 1, 2, 5, 7, 10, 14)) {
                for (lifted in listOf(emptySet(), setOf(0), setOf(2), setOf(0, 3))) {
                    for (opening in listOf(emptyList(), listOf(0), listOf(2), listOf(0, 4))) {
                        val row = HandFan.row(count, lifted, opening)
                        add(
                            "row $count ${lifted.sorted().joinToString(",").ifEmpty { "-" }} " +
                                "${opening.joinToString(",").ifEmpty { "-" }} = ${row.size}" +
                                row.places.joinToString("") { " ${it ?: -1}" }
                        )

                        add("step $count ${f(HandFan.step(band, layout.cardWidth, row.size, stepFraction))}")
                        for (place in 0 until row.size) {
                            add(
                                "centre $count $place ${row.size} " +
                                    "${f(HandFan.centreOf(band, layout.cardWidth, place, row.size, stepFraction))}"
                            )
                        }
                        // Swept across the band and past both ends, because the
                        // ends are where an off-by-one lives.
                        var i = -2
                        while (i <= 34) {
                            val x = band.left + band.width * (i / 32f)
                            add(
                                "insert $count ${f(x)} = " +
                                    HandFan.insertAt(band, layout.cardWidth, row, count, x, stepFraction)
                            )
                            i++
                        }
                        for (at in -1..count + 1) {
                            add("openingfor $count $at = ${row.openingFor(at, count) ?: -1}")
                            add("gapafter $count $at = ${row.gapAfter(at, count)}")
                        }
                        for (h in 0 until count) {
                            add("placeof $count $h = ${row.placeOf(h) ?: -1}")
                        }
                    }
                }
            }
            for (places in listOf(1, 3, 6, 12)) {
                for (place in 0 until places) {
                    val p = HandFan.pointFor(layout, place, places, stepFraction)
                    add("point $places $place ${f(p.x)} ${f(p.y)}")
                }
            }
        }
        write(
            "handfan.txt",
            "row/step/centre/insert/openingfor/gapafter/placeof/point (layout 320x226)",
            lines,
        )
    }

    /**
     * The smart movement: precedence, and hysteresis.
     *
     * Two things make this harder than "what is under the pointer". Precedence
     * has to be the same every time — piles beat a card beats a zone beats the
     * felt — and hysteresis means every threshold is a *pair*, so the intent you
     * already have is slightly sticky.
     *
     * That second half cannot be checked by sweeping a grid, because stickiness
     * is a function of what the last answer was. So most of this is **paths**:
     * the pointer walks a line and each answer is fed back as `previous`, which
     * is exactly what the real drag does. A grid sweep with no history checks
     * precedence; the paths check that the intent is sticky in the same places
     * and by the same amounts.
     *
     * The field is described in the vector file rather than rebuilt from a
     * script, because the resolver only reads the mat's ids and points and the
     * hand's size — so the C can construct exactly the same input without
     * replaying anything.
     *
     * **One thing this suite cannot reach, stated rather than left to look
     * tested.** `nearestZone` takes the *first* minimum, so an exact tie goes to
     * the earlier slot in the layout's insertion order. Flipping that to
     * last-wins changes nothing here and cannot: `resolve` takes a `MatPoint`,
     * so every candidate point makes a round trip through the mat's fractions,
     * and two distances that are equal in real arithmetic come back differing
     * in the last bit. It is a measure-zero case. `slotAt`'s tie-break is a
     * different matter and *is* tested — that one is reachable, because
     * rectangle containment with an inflation of exactly half the gap makes two
     * neighbours meet precisely on a midline.
     */
    @Test
    fun `drop targets`() {
        val layout = BoardLayouter.solve(400f, 240f, 0.686f, 1f, 0f)

        // A board with cards in a monster zone, a spell zone, and loose on the
        // felt — so the card-versus-zone contest is live rather than theoretical.
        val mat = listOf(
            PlacedCard(BoardCard(101, CardId(1001)), MatPoint(0.50f, 0.50f)),
            PlacedCard(BoardCard(102, CardId(1002)), MatPoint(0.36f, 0.82f)),
            PlacedCard(BoardCard(103, CardId(1003)), MatPoint(0.78f, 0.30f)),
        )
        val field = PlayField(mat = mat, hand = (0 until 5).map { BoardCard(200 + it, CardId(2000 + it)) })

        val lines = mutableListOf<String>()
        lines += "field ${field.hand.size} ${mat.size}"
        mat.forEach { lines += "card ${it.id} ${f(it.at.x)} ${f(it.at.y)}" }

        fun encode(intent: DropIntent): String = when (intent) {
            is DropIntent.Free -> "0 -1 - ${f(intent.at.x)} ${f(intent.at.y)}"
            is DropIntent.Zone -> "1 -1 ${slotName(intent.slot)} ${f(intent.at.x)} ${f(intent.at.y)}"
            is DropIntent.Stack -> "2 ${intent.onto} - 0 0"
            is DropIntent.Attach -> "3 ${intent.onto} - 0 0"
            is DropIntent.Hand -> "4 ${intent.at} - 0 0"
            DropIntent.Graveyard -> "5 -1 - 0 0"
            DropIntent.Banish -> "6 -1 - 0 0"
            DropIntent.Deck -> "7 -1 - 0 0"
            DropIntent.ExtraDeck -> "8 -1 - 0 0"
            DropIntent.Cancel -> "9 -1 - 0 0"
        }

        val hand = HandRow.of(field.hand.size)

        // --- 1. precedence, with no history ---------------------------------
        var iy = -4
        while (iy <= 28) {
            var ix = -4
            while (ix <= 28) {
                val point = MatPoint(ix / 24f, iy / 24f)
                for (attaching in listOf(false, true)) {
                    val intent = DropTargets.resolve(
                        point = point, dragged = 101, field = field, layout = layout,
                        previous = null, attaching = attaching, home = null,
                        hand = hand, handStep = 0.74f,
                    )
                    lines += "grid ${f(point.x)} ${f(point.y)} ${b(attaching)} = ${encode(intent)}"
                }
                ix++
            }
            iy++
        }

        // --- 1b. exact ties between adjacent zone centres --------------------
        //
        // `nearestZone` takes the first minimum, which is the layout's own
        // insertion order — the same rule `slotAt` resolves midline ties by. A
        // sweep on a grid never lands exactly on a midline, so the points are
        // constructed from the zone centres rather than hoped for.
        val zoneRects = layout.slots.entries.filter { it.key is BoardSlot.Zone }
        for (i in zoneRects.indices) {
            for (j in i + 1 until zoneRects.size) {
                val a = zoneRects[i].value
                val bRect = zoneRects[j].value
                val mx = (a.centerX + bRect.centerX) / 2f
                val my = (a.centerY + bRect.centerY) / 2f
                val point = layout.toMat(mx to my)
                val intent = DropTargets.resolve(
                    point = point, dragged = 101, field = field, layout = layout,
                    previous = null, attaching = false, home = null,
                    hand = hand, handStep = 0.74f,
                )
                lines += "grid ${f(point.x)} ${f(point.y)} 0 = ${encode(intent)}"
            }
        }

        // --- 2. paths, where the answer feeds back --------------------------
        data class Path(val name: String, val from: MatPoint, val to: MatPoint, val home: FanHome?)

        val homeAt = MatPoint(0.22f, 0.28f)
        val paths = listOf(
            // Across the mat through a zone and out again: the zone must latch
            // and then hold on longer than it took to take.
            Path("across", MatPoint(-0.10f, 0.50f), MatPoint(1.10f, 0.50f), null),
            // Down through the hand band.
            Path("intohand", MatPoint(0.50f, 0.30f), MatPoint(0.50f, 1.60f), null),
            // Onto a card and off it.
            Path("ontocard", MatPoint(0.20f, 0.50f), MatPoint(0.80f, 0.50f), null),
            // Toward the graveyard corner.
            Path("topile", MatPoint(0.50f, 0.50f), MatPoint(1.15f, 0.18f), null),
            // The put-back contest, unarmed and armed. The first must never
            // answer Cancel; the second must, and must still lose to a zone
            // that is pulling harder.
            Path("home-unarmed", MatPoint(0.60f, 0.60f), homeAt, FanHome(homeAt, departed = false)),
            Path("home-armed", MatPoint(0.60f, 0.60f), homeAt, FanHome(homeAt, departed = true)),
            Path("home-away", homeAt, MatPoint(0.62f, 0.34f), FanHome(homeAt, departed = true)),
        ) + run {
            // A home sitting *almost on top of* a zone centre, which is the one
            // configuration INCUMBENT_BIAS's cap exists for. CLAUDE.md gives
            // the measured numbers: a spread's hole comes within 0.072 card
            // widths of a zone centre at the head-height opening pitch, against
            // a bias of 0.12 — so an uncapped bias carries one target past the
            // *centre* of the other and makes the losing gesture unreachable no
            // matter how exactly it is aimed. Capping it at half the gap cannot
            // do that by construction.
            //
            // Without a path like this the cap is untested: uncapping it passed
            // 49,397 checks cleanly.
            val zone = layout[FieldZone.Monster(2)]!!
            val centre = layout.toMat(zone.centerX to zone.centerY)
            listOf(0.05f, 0.15f, 0.30f).map { offset ->
                val near = MatPoint(
                    centre.x + layout.cardWidth * offset / layout.field.width,
                    centre.y,
                )
                Path("home-nearzone-$offset", near, centre, FanHome(near, departed = true))
            }
        }

        for (path in paths) {
            // The home travels with the path rather than being hardcoded on
            // the other side. It was hardcoded, and the moment a path used a
            // different home the C resolved against the wrong point and read
            // as a port bug.
            lines += "home ${path.name} " +
                (path.home?.let { "${f(it.at.x)} ${f(it.at.y)} ${b(it.departed)}" } ?: "- - -")
            var previous: DropIntent? = null
            for (s in 0..48) {
                val k = s / 48f
                val point = MatPoint(
                    path.from.x + (path.to.x - path.from.x) * k,
                    path.from.y + (path.to.y - path.from.y) * k,
                )
                val intent = DropTargets.resolve(
                    point = point, dragged = 101, field = field, layout = layout,
                    previous = previous, attaching = false, home = path.home,
                    hand = hand, handStep = 0.74f,
                )
                lines += "path ${path.name} $s ${f(point.x)} ${f(point.y)} = ${encode(intent)}"
                previous = intent
            }
        }

        // --- 3. the latch arming ---------------------------------------------
        for (i in 0..24) {
            val landing = MatPoint(homeAt.x + i / 12f, homeAt.y)
            val seen = FanHome(homeAt, departed = false).seeing(landing, layout)
            lines += "arm ${f(landing.x)} ${f(landing.y)} = ${b(seen.departed)}"
        }

        write("droptargets.txt", "field/card, then grid/path/arm rows (layout 400x240)", lines)
    }

    /**
     * Carrying an intent out: every origin against every destination.
     *
     * `DropTargets` says *where* and `DragOrigin` says *from where*, and the
     * same destination means different things depending on the journey — a card
     * dropped on the graveyard leaves the mat if it was on the mat, leaves the
     * hand if it was in the hand, and is no move at all if it was already in the
     * graveyard. So the sweep is the full product, refusals included, and the
     * refusals are most of the value: "leaves the field untouched when it
     * refuses" is what the Kotlin gets from immutability and the C has to earn.
     *
     * Two asymmetries in here are the Kotlin's and are reproduced rather than
     * tidied. A pile-to-pile move keeps the card lying as it was, while the same
     * destination reached from the *mat* faces it up — because that branch goes
     * through `PlayField.toGraveyard` and the other does not. And a hand card
     * cannot reach the extra deck, while a mat card can.
     *
     * The board is rebuilt from the script before every case, so one case
     * cannot leave the next standing on a different table.
     */
    @Test
    fun `drop commit`() {
        val main = (1..16).map { CardId(1000 + it) }
        val extra = (1..4).map { CardId(9000 + it) }

        // A board with a stack (so Buried has something to name), a loose card,
        // cards in hand, and every pile non-empty.
        fun board(): PlayField {
            var f = PlayField.setUp(main, extra)
            repeat(4) { f = f.draw()!! }
            f = f.playFromHand(0, MatPoint(0.30f, 0.40f), CardPosition.FACE_UP_ATK)!!
            f = f.playFromHand(0, MatPoint(0.60f, 0.40f), CardPosition.FACE_UP_ATK)!!
            f = f.playFromHand(0, MatPoint(0.62f, 0.42f), CardPosition.FACE_DOWN_DEF)!!
            val top = f.mat.last().id
            val under = f.mat.first().id
            f = f.stackOnto(top, under)!!            // a real pile
            f = f.playFromDeck(0, MatPoint(0.80f, 0.70f), CardPosition.FACE_UP_ATK)!!
            f = f.toGraveyard(f.mat.last().id)!!     // something in the graveyard
            f = f.playFromDeck(0, MatPoint(0.20f, 0.70f), CardPosition.FACE_UP_ATK)!!
            // Banished *face-down*, which is the only way the pile-to-pile
            // asymmetry becomes visible: moving it on to the graveyard must
            // keep it face-down, where the same destination reached from the
            // mat would turn it face-up. With every pile card face-up already,
            // the two behaviours are indistinguishable and the test proves
            // nothing.
            f = f.toBanish(f.mat.last().id, faceDown = true)!!
            return f
        }

        val sample = board()
        val stacked = sample.mat.first { it.beneath.isNotEmpty() }

        val origins: List<Pair<String, DragOrigin>> = listOf(
            "hand0" to DragOrigin.Hand(0),
            "hand9" to DragOrigin.Hand(9),                       // out of range
            "mat" to DragOrigin.Mat(stacked.id),
            "matmissing" to DragOrigin.Mat(9999),
            "deck0" to DragOrigin.Pile(BoardSlot.Deck, 0),
            "gy0" to DragOrigin.Pile(BoardSlot.Graveyard, 0),
            "ban0" to DragOrigin.Pile(BoardSlot.Banished, 0),
            "extra0" to DragOrigin.Pile(BoardSlot.ExtraDeck, 0),
            "gy9" to DragOrigin.Pile(BoardSlot.Graveyard, 9),    // out of range
            "zone" to DragOrigin.Pile(BoardSlot.Zone(FieldZone.Monster(0)), 0), // not a pile
            "buried1" to DragOrigin.Buried(stacked.id, 1),
            "buried9" to DragOrigin.Buried(stacked.id, 9),       // nothing that deep
        )

        val loose = sample.mat.first { it.beneath.isEmpty() }.id
        val intents: List<Pair<String, DropIntent>> = listOf(
            "free" to DropIntent.Free(MatPoint(0.44f, 0.55f)),
            "zone" to DropIntent.Zone(BoardSlot.Zone(FieldZone.Monster(2)), MatPoint(0.5f, 0.5f)),
            "stack" to DropIntent.Stack(loose),
            "stackself" to DropIntent.Stack(stacked.id),
            "attach" to DropIntent.Attach(loose),
            "hand0" to DropIntent.Hand(0),
            "hand2" to DropIntent.Hand(2),
            "graveyard" to DropIntent.Graveyard,
            "banish" to DropIntent.Banish,
            "deck" to DropIntent.Deck,
            "extradeck" to DropIntent.ExtraDeck,
            "cancel" to DropIntent.Cancel,
        )

        val lines = mutableListOf<String>()

        // The board itself, so the C builds the same table without replaying.
        val base = board()
        lines += "setup ${main.size} ${extra.size}"
        lines += "build draw 4"
        lines += "build playhand 0 0.30 0.40 0"
        lines += "build playhand 0 0.60 0.40 0"
        lines += "build playhand 0 0.62 0.42 2"
        lines += "build stacktop"
        lines += "build playdeck 0 0.80 0.70 0"
        lines += "build gytop"
        lines += "build playdeck 0 0.20 0.70 0"
        lines += "build bantopfacedown"
        lines += "ids ${stacked.id} $loose"

        fun digest(f: PlayField): String = buildString {
            append("${f.mat.size}")
            f.mat.forEach { placed ->
                append(" ${placed.id}:${placed.card.position.ordinal}:${placed.beneath.size}")
                placed.beneath.forEach { append(",${it.instanceId}") }
                append(":${placed.card.materials.size}")
                placed.card.materials.forEach { append(",${it.instanceId}") }
            }
            append(" |")
            listOf(f.hand, f.deck, f.extraDeck, f.graveyard, f.banished).forEach { pile ->
                append(" ${pile.size}")
                pile.forEach { append(" ${it.instanceId}:${it.position.ordinal}") }
            }
        }

        for ((originName, origin) in origins) {
            for ((intentName, intent) in intents) {
                for (position in listOf(CardPosition.FACE_UP_ATK, CardPosition.FACE_DOWN_DEF)) {
                    val result = DropCommit.commit(base, origin, intent, position)
                    lines += "case $originName $intentName ${position.ordinal} " +
                        "= ${b(result != null)} ${digest(result ?: base)}"
                }
            }
        }
        write("dropcommit.txt", "setup/build/ids, then case <origin> <intent> <pos> = ok <digest>", lines)
    }

    /** The stable spelling of a slot, shared with the C by convention. */
    private fun slotName(slot: BoardSlot): String = when (slot) {
        is BoardSlot.Zone -> when (val z = slot.zone) {
            is FieldZone.Monster -> "M${z.index}"
            is FieldZone.ExtraMonster -> "E${z.index}"
            is FieldZone.SpellTrap -> "S${z.index}"
            FieldZone.FieldSpell -> "F"
        }
        BoardSlot.Deck -> "DECK"
        BoardSlot.ExtraDeck -> "EXTRA"
        BoardSlot.Graveyard -> "GY"
        BoardSlot.Banished -> "BAN"
    }
}
