package com.kaiharimoto.mastertool.core.ai.rules

/**
 * YGOrganization's database (db.ygoresources.com), captured live on 2026-10-04 for [YgoOrg].
 * [ASH] is `/data/card/12950` with its card data cut to the name, the outdated (English-only)
 * notes of section 0 cut to two and `qaIndex` to five of its 81 ids; [CALLED] is
 * `/data/card/13619` (Japanese FAQ only, no English meta) with section 1 cut to four notes.
 * [QA_24394] (up to date) and [QA_6417] (a legacy, unconfirmable translation) are verbatim.
 * [INDEX] is ten entries of `/data/idx/card/name/en`, among them an old name, quoted names and
 * one with a no-break space. [QA_NOTES] is built by hand on 24394, to the shape the site's
 * own script reads (`notes.invalid_tcg`/`notes.precedent`, each `[{"body": …}]`), with an
 * outdated English; [RETRACTED] likewise, with its English marked `zombie`.
 */
object YgoOrgFixture {
    val ASH = """{"cardData": {"en": {"name": "Ash Blossom & Joyous Spring", "id": 12950}, "ja": {"name": "灰流うらら"}}, "cardId": 12950, "faqData": {"entries": {"0": [{"en": "This card's effect is a Quick Effect that activates in your hand."}, {"en": "It does not target and can optionally be chained to the activation of a card or an effect that includes any of the \"●\" effects."}], "1": [{"en": "About this card's ① st effect:", "ja": "【①の効果について】"}, {"en": "This effect is a Quick Effect, which can be activated in the Hand.", "ja": "手札で発動できる誘発即時効果です。"}, {"ja": "●のいずれかを含む魔法・罠・モンスターの効果が発動した時に、直接チェーンして発動できます。"}, {"en": "You cannot activate it during the Damage Step.", "ja": "ダメージステップには発動できません。"}, {"ja": "直前のチェーンブロック１つ分の効果処理が無効化されます。（チェーンブロック１つの効果処理内に●に該当する処理と該当しない処理が含まれている場合でも、チェーンブロック１つ分の効果処理が無効化されることでそれらの処理はいずれも適用されなくなります。）"}]}, "meta": {"en": {"date": "2020-04-22", "misc": "pazim", "type": 4}, "ja": {"date": "2022-03-02", "type": 1}}}, "qaIndex": [6417, 11022, 23940, 24162, 24394]}"""

    val CALLED = """{"cardData": {"en": {"name": "Called by the Grave"}}, "cardId": 13619, "faqData": {"entries": {"1": [{"en": "About this card's ① st effect:", "ja": "【①の効果について】"}, {"en": "You cannot activate it during the Damage Step.", "ja": "ダメージステップには発動できません。"}, {"ja": "通常モンスターを対象として発動することもできます。"}, {"ja": "処理時に、対象のモンスターを除外します。除外した場合、ただちに『次のターンの終了時まで、この効果で除外したモンスター及びそのモンスターと元々のカード名が同じモンスターの効果は無効化される』効果を適用します。"}]}, "meta": {"ja": {"date": "2025-02-21", "type": 1}}}, "qaIndex": [23972, 23981, 24077, 24167, 24250]}"""

    val QA_24394 = """{"cards": [12950, 23585], "notes": {}, "qaData": {"en": {"answer": "If a Set <<23585>> is activated, the effect of <<12950>> can be activated in response.\n(If <<23585>> is activated from the hand, the effect of <<12950>> cannot be activated in response.)\n\nIn addition, whether the opponent has a Level 5 or higher monster in their hand or not doesn't make a difference.", "id": 24394, "question": "Can the effect of <<12950>> be activated in response to the activation of <<23585>>?", "thisSrc": {"date": "2026-09-26", "misc": "pyrQ", "type": 4}, "title": "Can the effect of <<12950>> be activated in response to the activation of <<23585>>?", "tlSrc": {"date": "2026-09-25", "type": 0}, "translationStatus": "confirmed"}, "ja": {"answer": "セットされていた「<<23585>>」を発動したのであれば、チェーンして「<<12950>>」の効果を発動できます。\n（手札から「<<23585>>」を発動した場合は、チェーンして「<<12950>>」の効果を発動することはできません。）\n\nなお、相手の手札にレベル５以上のモンスターが存在するかどうかは考慮しません。", "id": 24394, "question": "「<<23585>>」を発動した時に、チェーンして「<<12950>>」の効果を発動できますか？", "thisSrc": {"date": "2026-09-25", "type": 0}, "title": "「<<23585>>」の発動にチェーンして「<<12950>>」の効果を発動できますか？"}}, "tags": ["k:Monster"]}"""

    val QA_6417 = """{"cards": [5551, 8993, 12950], "notes": {}, "qaData": {"en": {"answer": "In this scenario, if the effect of <<5551>> was negated by the effect of <<12950>>, your opponent does not look in their Deck for the declared card, so neither \"●\" effect can be chosen. In this case, you can activate <<8993>> during this turn.", "id": 6417, "question": "When I activate <<5551>>, my opponent chains the effect of <<12950>>, and negates the effect. During this turn, can I activate <<8993>>?", "thisSrc": {"date": "2017-08-07", "misc": "???", "type": 4}, "title": "When I activate <<5551>>, my opponent chains the effect of <<12950>>, and negates the effect. During this turn, can I activate <<8993>>?", "tlSrc": {"date": "2017-08-04", "type": 0}, "translationStatus": "unconfirmable"}, "ja": {"answer": "質問の状況の場合、相手の「<<12950>>」のモンスター効果によって、「<<5551>>」の効果が無効になり、『自身のデッキを確認し、宣言されたモンスターがあった場合、その内の１体をお互いに確認し以下の効果から１つを選択して適用する』処理自体が行われていませんので、どちらの『●』の効果も適用される事はありません。\n\nこの場合、自分はこのターンに「<<8993>>」を発動する事ができます。", "id": 6417, "question": "自分が「<<5551>>」を発動した際に、相手がチェーンして手札の「<<12950>>」の『①：以下のいずれかの効果を含む魔法・罠・モンスターの効果が発動した時、このカードを手札から捨てて発動できる。その効果を無効にする』モンスター効果を発動し、「<<5551>>」の効果が無効になりました。\n\nこのターン、自分は「<<8993>>」を発動する事はできますか？", "thisSrc": {"date": "2017-08-04", "type": 0}, "title": "「<<5551>>」の効果が無効になったターン、自分は「<<8993>>」を発動できますか？"}}, "tags": ["k:Chain"]}"""

    val INDEX = """{"\"A Case for K9\"": [21385], "Ash Blossom & Joyous Spring": [12950], "Ghost Ash & Beautiful Spring": [12950], "Called by the Grave": [13619], "Flashforce Sword": [23585], "Lullaby of Obedience": [5551], "Pot of Duality": [8993], "\"Infernoble Arms - Durendal\"": [15287], "\"Infernoble Arms - Durendal\"": [15287], "\"Flame Noble Arms - Durendal\"": [15287]}"""

    val QA_NOTES = """{"cards":[12950,23585],"notes":{"invalid_tcg":[{"body":"The TCG's text of <<23585>> reads differently here."}],"precedent":[{"body":"responding to a Set card's activation"}]},"qaData":{"en":{"answer":"Old English answer.","id":24395,"question":"Old English question about <<12950>>?","thisSrc":{"date":"2026-09-26","type":4},"tlSrc":{"date":"2026-09-25","type":0},"translationStatus":"outdated"},"ja":{"answer":"できます。","id":24395,"question":"「<<23585>>」に「<<12950>>」をチェーンできますか？","thisSrc":{"date":"2026-10-01","type":0}}}}"""

    val RETRACTED = """{"cards":[12950],"notes":{},"qaData":{"en":{"answer":"Gone.","id":24396,"question":"Gone?","thisSrc":{"date":"2020-01-01","type":4},"translationStatus":"zombie"}}}"""
}
