#!/usr/bin/env python3
"""Writes Ai's traced head as Kotlin: geometry.json -> AvatarGeometry.kt in :core.

    python3 tools/avatar/gen.py

geometry.json is the head as kai approved it (the mockup's v7): the silhouette and
net from design4.js (geometry4.json), with the eyes drawn at 95 % of their fitted
size and both 81.6 px tall. Every number is a pixel of the 465 x 352 reference.
"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', '..', 'app', 'core', 'src', 'commonMain', 'kotlin', 'com', 'kaiharimoto',
                   'mastertool', 'core', 'ai', 'avatar', 'AvatarGeometry.kt')
g = json.load(open(os.path.join(HERE, 'geometry.json')))


def num(v):
    s = ('%.2f' % v).rstrip('0').rstrip('.')
    return (s if s not in ('-0', '') else '0') + 'f'


def floats(values, indent):
    out, line = [], []
    for v in values:
        line.append(num(v))
        if len(line) == 12:
            out.append(indent + ', '.join(line) + ',')
            line = []
    if line:
        out.append(indent + ', '.join(line) + ',')
    return '\n'.join(out)


def path(segs):
    """M x y, then c1 c2 end for each cubic: 2 + 6n numbers."""
    v = list(segs[0][0])
    for s in segs:
        v += s[1] + s[2] + s[3]
    return v


def oval(o):
    return 'Oval(%s, %s, %s, %s, %s)' % tuple(num(o[k]) for k in ('cx', 'cy', 'rx', 'ry', 'tilt'))


def eye(e):
    return 'EyeBase(%s, %s, %s, %s, %s, %s)' % tuple(num(e[k]) for k in ('cx', 'cy', 'rx', 'ry', 'tilt', 'n'))


veins = []
for l in g['lines']:
    veins.append('        Vein(\n            "%s",\n            floatArrayOf(\n%s\n            ),\n            %s,\n            closed = %s,\n        ),' % (
        l['name'], floats(path(l['segs']), ' ' * 16), num(l['w']), 'true' if l['closed'] else 'false'))

kt = '''package com.kaiharimoto.mastertool.core.ai.avatar

// Generated by tools/avatar/gen.py from tools/avatar/geometry.json. Do not edit by hand:
// change the design there and run it again.

/**
 * Ai's head as traced and redrawn (the mockup's v7, approved by kai): pixels of the
 * %dx%d reference. [body] is the silhouette, a closed run of cubics; [veins] the
 * net, stroked and clipped to the body; [cheeks] the two ovals the spokes meet;
 * [eyeL] and [eyeR] the eyes as fitted and then drawn at 95 %%, both %s px tall.
 * A path is `x0, y0` then `c1x, c1y, c2x, c2y, x, y` for each cubic.
 */
object AvatarGeometry {
    const val WIDTH = %s
    const val HEIGHT = %s

    val body = floatArrayOf(
%s
    )

    val veins = listOf(
%s
    )

    val cheeks = listOf(%s)

    val eyeL = %s
    val eyeR = %s

    /** The bottom of the chin, which the head squashes and leans about. */
    const val PIVOT_X = %s
    const val PIVOT_Y = %s

    /** The mask ring's centre and tilt, and how far down its flat bottom sits: the sleep bubble rises from there. */
    const val RING_X = %s
    const val RING_Y = %s
    const val RING_TILT = %s
    const val RING_DEPTH = %s
}
''' % (g['W'], g['H'], num(g['eyes']['L']['ry'] * 2)[:-1],
       num(g['W']), num(g['H']),
       floats(path(g['bodySegs']), ' ' * 8),
       '\n'.join(veins),
       ', '.join(oval(n) for n in g['nodes']),
       eye(g['eyes']['L']), eye(g['eyes']['R']),
       num(g['chin']['mid'][0]), num(g['chin']['low']),
       num(g['ring']['cx']), num(g['ring']['cy']), num(g['ring']['tilt']), num(g['ring']['bottomDepth']))
os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, 'w').write(kt)
print('wrote', os.path.relpath(OUT, os.path.join(HERE, '..', '..')))
