package com.kaiharimoto.mastertool.core.ai.chessy

// Generated by tools/chessy/ears.py from Chessy's pack. Never edit by hand: run the script again.

/**
 * Chessy's ears mark (kai: "a small silhouette of her ears"): the outline of each ear where it shows above her head,
 * as x, y pairs in one box whose width is 1 and whose height is [HEIGHT]. Drawn filled, in ink.
 */
object ChessyEars {
    const val HEIGHT = 0.5314f

    val LEFT = floatArrayOf(0.1452f, 0.0403f, 0.1335f, 0.0403f, 0.1246f, 0.0466f, 0.1004f, 0.0896f, 0.0591f, 0.2007f, 0.0403f, 0.2867f, 0.0143f, 0.3056f, 0.0332f, 0.3289f, 0.0323f, 0.3548f, 0.0215f, 0.3665f, 0.0215f, 0.3844f, 0.0018f, 0.4319f, 0.0000f, 0.4552f, 0.0179f, 0.4704f, 0.0152f, 0.4991f, 0.0314f, 0.5287f, 0.0358f, 0.5269f, 0.0547f, 0.4892f, 0.0842f, 0.4444f, 0.1228f, 0.3943f, 0.1729f, 0.3405f, 0.1765f, 0.3271f, 0.1873f, 0.3262f, 0.2222f, 0.2939f, 0.2634f, 0.2670f, 0.3056f, 0.2482f, 0.3719f, 0.2321f, 0.3746f, 0.2240f, 0.3324f, 0.1676f, 0.2760f, 0.1156f, 0.2195f, 0.0753f)

    val RIGHT = floatArrayOf(0.8459f, 0.0000f, 0.7608f, 0.0475f, 0.7151f, 0.0806f, 0.6371f, 0.1577f, 0.6030f, 0.2016f, 0.5968f, 0.2168f, 0.5995f, 0.2231f, 0.6093f, 0.2258f, 0.6102f, 0.2321f, 0.6711f, 0.2464f, 0.7142f, 0.2643f, 0.7590f, 0.2930f, 0.7975f, 0.3280f, 0.8056f, 0.3280f, 0.8091f, 0.3396f, 0.8575f, 0.3916f, 0.9014f, 0.4489f, 0.9274f, 0.4884f, 0.9471f, 0.5278f, 0.9597f, 0.5314f, 0.9686f, 0.5099f, 0.9776f, 0.5090f, 0.9866f, 0.4946f, 0.9875f, 0.4785f, 0.9794f, 0.4444f, 0.9937f, 0.4453f, 1.0000f, 0.4364f, 0.9919f, 0.4005f, 0.9740f, 0.3602f, 0.9740f, 0.3450f, 0.9615f, 0.3289f, 0.9597f, 0.3047f, 0.9803f, 0.2805f, 0.9740f, 0.2724f, 0.9516f, 0.2599f, 0.9346f, 0.1864f, 0.9167f, 0.1353f, 0.8772f, 0.0493f, 0.8504f, 0.0009f)
}
