"""Chessy's ears mark: the outline of her two ears where they show above her head, traced from the pack.

    python3 tools/chessy/ears.py app/neue/src/commonMain/composeResources/files/chessy \
        app/core/src/commonMain/kotlin/com/kaiharimoto/mastertool/core/ai/chessy/ChessyEars.kt

kai: "use a small silhouette of her ears if she's mentioned and you need a small monogram for her". Each ear is the
ear layer's alpha less everything drawn over it (the head and hair), its outer edge simplified to a few dozen points
and set in one box, the pair's width 1. Writes ChessyEars.kt, which is generated: never edit it by hand.
"""
import json
import os
import sys

import cv2
import numpy as np
from PIL import Image

src, dst = sys.argv[1], sys.argv[2]
pack = json.load(open(os.path.join(src, 'chessy.json')))
W, H = pack['w'], pack['h']
layers = {l['id']: l for l in pack['layers']}


def alpha(ids):
    a = np.zeros((H, W), np.uint8)
    for i in ids:
        p = layers[i]['pic']
        im = np.asarray(Image.open(os.path.join(src, p['file'])).convert('RGBA'))[..., 3]
        box = a[p['y']:p['y'] + p['h'], p['x']:p['x'] + p['w']]
        np.maximum(box, im, out=box)
    return a


over = alpha([l['id'] for l in pack['layers'] if l.get('pic') and l['id'] not in ('ear-l', 'ear-r')])
outlines = []
for ear in ('ear-l', 'ear-r'):
    shown = ((alpha([ear]) > 128) & (over <= 128)).astype(np.uint8)
    shown = cv2.morphologyEx(shown, cv2.MORPH_OPEN, cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (9, 9)))
    contours, _ = cv2.findContours(shown, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
    c = max(contours, key=cv2.contourArea)
    outlines.append(cv2.approxPolyDP(c, 3.0, True)[:, 0, :].astype(np.float32))

pts = np.concatenate(outlines)
x0, y0 = pts.min(0)
span = (pts.max(0) - pts.min(0))
scale = 1.0 / span[0]


def floats(o):
    n = (o - [x0, y0]) * scale
    return ', '.join(f'{v:.4f}f' for v in n.flatten())


body = f'''package com.kaiharimoto.mastertool.core.ai.chessy

// Generated by tools/chessy/ears.py from Chessy's pack. Never edit by hand: run the script again.

/**
 * Chessy's ears mark (kai: "a small silhouette of her ears"): the outline of each ear where it shows above her head,
 * as x, y pairs in one box whose width is 1 and whose height is [HEIGHT]. Drawn filled, in ink.
 */
object ChessyEars {{
    const val HEIGHT = {span[1] * scale:.4f}f

    val LEFT = floatArrayOf({floats(outlines[0])})

    val RIGHT = floatArrayOf({floats(outlines[1])})
}}
'''
open(dst, 'w').write(body)
print('ears', [len(o) for o in outlines], 'points, height', round(float(span[1] * scale), 4))
